### ISSUE TITLE
Performance and improvements

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#6] opened 2021-01-19 11:51 UTC
We ha added Torrest as an option torrent downloader in our [Alfa add-on](https://github.com/alfa-addon/addon).  After testing Torrest for few days we have some issues/questions/improvements:

-	Is there a way to limit the concurrent number of downloading torrents?  Let say I need to download a series season.  That may generate 10 torrents.  For smaller devices it might be wise to let only a few torrents concurrently downloading while the rest stay queued waiting for an open slot.  Tried “Connections Limit” without success.

-	Can you add a function to call Torrest to download from a torrent filename?  Here is an example of a code for navigation.py that might work:

```
@plugin.route("/play_path")
@check_playable
@query_arg("path")
def play_file(path, buffer=True):
	info_hash = api.add_torrent(path, ignore_duplicate=True)
	play_info_hash(info_hash, buffer=buffer)

```
-	On doing some performance testing I have found that comparing a torrent download of the same torrent file in the same conditions, stand-alone, Python binding Libtorrent-rasterbar v2.0.2 is about twice faster that Torrest with internal Libtorrent-rasterbar v1.2.11.  How can Torrest performance be improved?

I have sent you emails to your i96751414@gmail.com account providing  more details about how Alfa works and ways for further cooperation.

Regards,
Alfa Team

**Comment by i96751414** [comment] 2021-01-19 15:25
- "Connections Limit" should be the way to go. I'll double check if it's working as expected or not.
- Done!
- This is something hard to test, as more speed does not mean it is better (for instance, in case you download the same piece multiple times). To make sure we are running good tests I need you to provide me:
   - the torrent you are using (i.e., one from archive.org); 
   - the stats (particularly how much time it take to achieve 100%; average download rate; etc) when using both clients;
   - the configuration used with both clients (libtorrent v2.0.2 in particular).

**Comment by lopezvg** [comment] 2021-01-22 12:38
- Have you checked the "Connections Limit" behavior or other ways to limit the total number of downloading torrents?
- Thanks!
- Doing a more careful speed testing, I have arrived to the following conclusions with a 300/300 Mb/s fiber connection, so we can drop the issue:
    - Using W10 it get the max speed
    - Using Android, by doing the tests through a Teamviwer connection impacted negatively on performance.  
    - By doing the Android test on its native screen a reasonable speed was met, reaching about 200 Mb/s.  With Quasar, similar results were obtained, so the Android box architecture was limiting the speed in all cases.

**Comment by i96751414** [comment] 2021-01-22 12:40
Nice :) I still have to investigate the connections limit behaviour, but at first glance it seems to be working as expected.
Hopefully today I will have the time to check that.

**Comment by i96751414** [comment] 2021-01-22 16:02
I can confirm the connections limit is working as intended.

**Comment by lopezvg** [comment] 2021-01-22 17:31
I'm a bit confused.  Please give me some guidance.  For example, if I want a max of 5 concurrent torrents downloading, what value should I set in "Connections Limit"?

On using http://127.0.0.1:61235/torrents/?status=true, should not be the 5 downloading torrents in "status": {"state": 3}, and the order waiting torrents in "status": {"state": 0} (queued)?

**Comment by i96751414** [comment] 2021-01-22 18:32
Connections Limit does not limit the number of torrents you download in parallel but the number of global connections used for **all** the torrents, like a real torrent engine would do. By lowering this limit, you will use less CPU but will also have a smaller download rate. If you really want to pause some torrents, I am afraid the only option is to do it manually.

**Comment by lopezvg** [comment] 2021-01-22 18:41
Ok, understood.  The reason I'm asking is because Quasar does control the number of concurrent downloads.  It is not configurable, but it is set to 3.  That is the rationale behind my first question: could Torrest do something like that, but with a configurable value? 

I understand it is not a currently available feature, but I wonder if it could be implemented with a reasonable cost...

**Comment by i96751414** [comment] 2021-01-22 18:49
Are you sure about that? I don't use Quasar for a really long time ago, but I don't remember of a maximum value of concurrent downloads.

Imagine we wanted to implement that.. How would we decide what torrents to resume (when a torrent completes the download)? How would we decide which torrents to pause when a batch of torrents is added? I think this would only be possible by saving some kind of state internally.

**Comment by i96751414** [comment] 2021-01-22 19:01
Maybe there's a way to do kind of what you want :)

**Comment by lopezvg** [comment] 2021-01-22 19:06
I'm quite sure it would not let more than 3 simultaneous downloads .

For what I have seen, it works like a FIFO queue.  When a downloading torrent is paused, finished o seeding, it frees its slot and the first available torrent starts downloading.  Those torrents waiting for slot are set in "queue" state, and incoming torrents with no slot available are also set in "queue" state. 

Quasar maintain a kind of database with the sessions

**Comment by lopezvg** [comment] 2021-01-22 19:27
> Maybe there's a way to do kind of what you want :) https://libtorrent.org/manual-ref.html#queuing
> I will play with it later today.. If possible, I will add it

Excellent!!!

**Comment by i96751414** [comment] 2021-01-22 21:03
It seems this limit (max 3 torrents downloading) is also available in Torrest by default, you just don't get the "Queued" status string. I am making this limit configurable

**Comment by i96751414** [comment] 2021-01-23 16:04
Are you able to check the Spanish translations I've just added?

**Comment by lopezvg** [comment] 2021-01-23 18:19
> Are you able to check the Spanish translations I've just added?

Two changes: the first uses "a semillar" por "seeding" and the second was missing a tilde:

```
msgctxt "#30072"
msgid "Maximum number of simultaneous seeding torrents"
msgstr "Número máximo de torrents a semillar simultáneamente"

msgctxt "#30078"
msgid "Limits"
msgstr "Límites"
```

**Comment by i96751414** [comment] 2021-01-26 19:33
I am closing this issue as I believe everything discussed here has been addressed (and will be available on the next release).
Feel free to open it again in case something was not clear.

**Closed by i96751414** 2021-01-26 19:33 UTC
